api:
  client:
    insecure_skip_verify: false
    credentials_path: /etc/crowdsec/local_api_credentials.yaml
  server:
    log_level: info
    listen_uri: 0.0.0.0:9090
    profiles_path: /etc/crowdsec/profiles.yaml
    trusted_ips:
      - 0.0.0.0/0
      - 127.0.0.1
      - ::1