app:
    base_url: http://localhost:3000
    log_level: warning
    save_logs: false

server:
    external_port: 3000
    internal_port: 3001
    internal_hostname: pangolin
    secure_cookies: true

traefik:
    cert_resolver: letsencrypt
    http_entrypoint: web
    https_entrypoint: websecure

gerbil:
    start_port: 51820
    base_endpoint: localhost
    block_size: 16
    subnet_group: 10.0.0.0/8 

rate_limit:
    window_minutes: 1
    max_requests: 100