app:
    base_url: https://fossorial.io
    log_level: debug
    save_logs: false

server:
    external_port: 3000
    internal_port: 3001
    internal_hostname: pangolin
    secure_cookies: false
    session_cookie_name: session
    resource_session_cookie_name: resource_session

traefik:
    cert_resolver: letsencrypt
    http_entrypoint: web
    https_entrypoint: websecure
    prefer_wildcard_cert: true

gerbil:
    start_port: 51820
    base_endpoint: fossorial.io
    use_subdomain: false
    block_size: 16
    subnet_group: 10.0.0.0/8

rate_limit:
    window_minutes: 1
    max_requests: 100

email:
    smtp_host: host.hoster.net
    smtp_port: 587
    smtp_user: no-reply@example.io
    smtp_pass: aaaaaaaaaaaaaaaaaa
    no_reply: no-reply@example.io
