app:
    name: Pangolin
    base_url: http://localhost:3000
    log_level: warning
    save_logs: false

server:
    external_port: 3000
    internal_port: 3001
    internal_hostname: pangolin
    secure_cookies: true

traefik:
    cert_resolver: letsencrypt
    http_entrypoint: web
    https_entrypoint: websecure

rate_limit:
    window_minutes: 1
    max_requests: 100