app:
    name: Pangolin
    base_url: http://localhost:3000
    log_level: debug
    save_logs: "false"

server:
    external_port: "3000"
    internal_port: "3001"
    internal_hostname: localhost
    secure_cookies: "false"

traefik:
    cert_resolver: "letsencrypt"
    http_entrypoint: "http"
    https_entrypoint: "https"

rate_limit:
    window_minutes: "1"
    max_requests: "100"
