app:
    name: Pangolin
    environment: dev
    base_url: http://localhost:3000
    log_level: debug
    save_logs: "false"
    secure_cookies: "false"

server:
    external_port: "3000"
    internal_port: "3001"

rate_limit:
    window_minutes: "1"
    max_requests: "100"
