app:
    dashboard_url: "http://localhost:3002"
    base_domain: "localhost"
    log_level: "info"
    save_logs: false

server:
    external_port: 3000
    internal_port: 3001
    next_port: 3002
    internal_hostname: "pangolin"
    secure_cookies: true
    session_cookie_name: "p_session"
    resource_session_cookie_name: "p_resource_session"
    resource_access_token_param: "p_token"

traefik:
    cert_resolver: "letsencrypt"
    http_entrypoint: "web"
    https_entrypoint: "websecure"

gerbil:
    start_port: 51820
    base_endpoint: "localhost"
    block_size: 24
    site_block_size: 30
    subnet_group: 100.89.137.0/20
    use_subdomain: true

rate_limits:
    global:
        window_minutes: 1
        max_requests: 100

users:
    server_admin:
        email: "admin@example.com"
        password: "Password123!"

flags:
    require_email_verification: false
    disable_signup_without_invite: true
    disable_user_create_org: true
