app:
    dashboard_url: http://localhost
    base_domain: localhost
    log_level: debug
    save_logs: false

server:
    external_port: 3000
    internal_port: 3001
    next_port: 3002
    internal_hostname: localhost
    secure_cookies: false
    session_cookie_name: p_session
    resource_session_cookie_name: p_resource_session

traefik:
    cert_resolver: letsencrypt
    http_entrypoint: web
    https_entrypoint: websecure

gerbil:
    start_port: 51820
    base_endpoint: localhost
    block_size: 16
    site_block_size: 29
    subnet_group: 10.0.0.0/8
    use_subdomain: true

rate_limits:
    global:
        window_minutes: 1
        max_requests: 100

users:
    server_admin:
        email: admin@example.com
        password: Password123!

flags:
    require_email_verification: false
